name: admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  provider: ^6.1.2
  get: ^4.6.1
  pdf: ^3.11.1
  badges: ^3.1.2
  get_storage: ^2.1.1
  excel: ^4.0.6
  file_saver: ^0.2.14
  intl: ^0.20.1
  timeago: ^3.2.2
  dotted_border: ^2.1.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
