import { Request, Response, NextFunction } from 'express';
import { createPermission } from './permissionController/createPermission';
import { getPermissions } from './permissionController/getPermissions';
import { getPermissionById } from './permissionController/getPermissionById';
import { updatePermission } from './permissionController/updatePermission';
import { deletePermission } from './permissionController/deletePermission';
import { initializeDefaultPermissions } from './permissionController/initializeDefaultPermissions';
import { getPermissionsByRole } from './permissionController/getPermissionsByRole';
import { addPermission } from './permissionController/addPermission';
import { removePermission as removePermissionController } from './permissionController/removePermission';
import { getRoleMatrix } from './permissionController/getRoleMatrix';
import { getResourcePermissions } from './permissionController/getResourcePermissions';
import { AppError, errorCodes } from '../utils/errors';

export const createPermissionController = createPermission;
export const getPermissionsController = getPermissions;
export const getPermissionByIdController = getPermissionById;
export const updatePermissionController = updatePermission;
export const deletePermissionController = deletePermission;
export const initializeDefaultPermissionsController = initializeDefaultPermissions;
export const getPermissionsByRoleController = getPermissionsByRole;
export const addPermissionController = addPermission;
export const removePermissionController = removePermissionController;
export const getRoleMatrixController = getRoleMatrix;
export const getResourcePermissionsController = getResourcePermissions;
