export const errorCodes = {
  // Article related errors
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
  INVALID_ARTICLE_DATA: 'INVALID_ARTICLE_DATA',
  
  // General errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_PRICE_RANGE: 'INVALID_PRICE_RANGE',
  INVALID_SERVICE: 'INVALID_SERVICE',
  
  // Order related errors
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_ORDER_DATA: 'INVALID_ORDER_DATA',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  ORDER_UPDATE_FAILED: 'ORDER_UPDATE_FAILED',
  ORDERS_FETCH_FAILED: 'ORDERS_FETCH_FAILED',
  ZONE_ORDERS_FETCH_FAILED: 'ZONE_ORDERS_FETCH_FAILED',
  ROUTE_CALCULATION_FAILED: 'ROUTE_CALCULATION_FAILED',
  ROUTE_GENERATION_FAILED: 'ROUTE_GENERATION_FAILED',
  STATS_FETCH_FAILED: 'STATS_FETCH_FAILED',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_USER_PROFILE: 'INVALID_USER_PROFILE',
  ONE_CLICK_ORDER_FAILED: 'ONE_CLICK_ORDER_FAILED',

  // Billing related errors
  BILL_CREATION_FAILED: 'BILL_CREATION_FAILED',
  BILL_FETCH_FAILED: 'BILL_FETCH_FAILED',
  USER_BILLS_FETCH_FAILED: 'USER_BILLS_FETCH_FAILED',
  BILL_UPDATE_FAILED: 'BILL_UPDATE_FAILED',
  LOYALTY_POINTS_FETCH_FAILED: 'LOYALTY_POINTS_FETCH_FAILED',
  LOYALTY_POINTS_UPDATE_FAILED: 'LOYALTY_POINTS_UPDATE_FAILED',
  REWARD_NOT_FOUND: 'REWARD_NOT_FOUND',
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  POINTS_REDEMPTION_FAILED: 'POINTS_REDEMPTION_FAILED',
  SUBSCRIPTION_UPDATE_FAILED: 'SUBSCRIPTION_UPDATE_FAILED',
  SUBSCRIPTION_FETCH_FAILED: 'SUBSCRIPTION_FETCH_FAILED',
  SUBSCRIPTION_CANCELLATION_FAILED: 'SUBSCRIPTION_CANCELLATION_FAILED',
  BILLING_STATS_FETCH_FAILED: 'BILLING_STATS_FETCH_FAILED',

  // Zone related errors
  ZONE_CREATION_FAILED: 'ZONE_CREATION_FAILED',
  ZONE_FETCH_FAILED: 'ZONE_FETCH_FAILED',
  ZONES_FETCH_FAILED: 'ZONES_FETCH_FAILED',
  ZONE_UPDATE_FAILED: 'ZONE_UPDATE_FAILED',
  ZONE_DELETE_FAILED: 'ZONE_DELETE_FAILED',
  ZONE_HAS_ACTIVE_ORDERS: 'ZONE_HAS_ACTIVE_ORDERS',
  ZONE_STATS_FETCH_FAILED: 'ZONE_STATS_FETCH_FAILED',

  // Delivery related errors
  DELIVERY_PERSON_NOT_FOUND: 'DELIVERY_PERSON_NOT_FOUND',
  DELIVERY_SLOT_NOT_FOUND: 'DELIVERY_SLOT_NOT_FOUND',
  DELIVERY_PERSON_ASSIGNMENT_FAILED: 'DELIVERY_PERSON_ASSIGNMENT_FAILED'
} as const;

export class AppError extends Error {
  statusCode: number;
  errorCode: string;

  constructor(statusCode: number, message: string, errorCode: string) {
    super(message);
    this.statusCode = statusCode;
    this.errorCode = errorCode;
  }
}
