export enum LoyaltyEventType {
  POINTS_EARNED = 'POINTS_EARNED',
  POINTS_REDEEMED = 'POINTS_REDEEMED',
  REWARD_CREATED = 'REWARD_CREATED',
  REWARD_REDEEMED = 'REWARD_REDEEMED',
  REWARD_UPDATED = 'REWARD_UPDATED',
  REWARD_DELETED = 'REWARD_DELETED',
  TIER_UPGRADED = 'TIER_UPGRADED',
  TIER_DOWNGRADED = 'TIER_DOWNGRADED',
  POINTS_ADJUSTED = 'POINTS_ADJUSTED',
  POINTS_EXPIRED = 'POINTS_EXPIRED',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_UPDATED = 'ACCOUNT_UPDATED',
  PROGRAM_CREATED = 'PROGRAM_CREATED',
  PROGRAM_UPDATED = 'PROGRAM_UPDATED',
  PROGRAM_DELETED = 'PROGRAM_DELETED'
}

export interface LoyaltyEvent {
  id?: string;
  userId: string;
  type: LoyaltyEventType;
  details: string;
  metadata?: Record<string, any>;
  createdAt: string;
}
