name: prima
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  spring_button: ^2.0.0
  flutter_svg: ^2.0.0
  http: ^1.2.2
  cookie_jar: ^4.0.8
  path_provider: ^2.1.1
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  supabase_flutter: ^2.8.2
  flutter_dotenv: ^5.2.1
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shared_preferences: ^2.2.2
  path_provider_platform_interface: ^2.1.1
  path_provider_foundation: ^2.3.1
  path_provider_android: ^2.2.1
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/AlphaLogo.png
    - assets/Building.png
    - assets/Adresse_back.png
    - assets/google-icon.png
    - assets/Lavage.png
    - assets/map-icon.svg
    - assets/menu-icon.svg
    - assets/Nettoyage_à_sec.png
    - assets/Pliage.png
    - assets/promo-img1.png
    - assets/Repassage.png
    - assets/source-sans-pro/
